-- Auto-generated by Matugen

local c = {
  background = '#1a1110',
  background_custom = '#ffb4ab',
  background_custom_container = '#73332e',
  background_custom_source = '#1a1110',
  background_custom_value = '#1a1110',
  error = '#ffb4ab',
  error_container = '#93000a',
  inverse_on_surface = '#392e2d',
  inverse_primary = '#904a43',
  inverse_surface = '#f1dedc',
  on_background = '#f1dedc',
  on_background_custom = '#561e1a',
  on_background_custom_container = '#ffdad6',
  on_error = '#690005',
  on_error_container = '#ffdad6',
  on_primary = '#561e19',
  on_primary_container = '#ffdad6',
  on_primary_fixed = '#3b0907',
  on_primary_fixed_variant = '#73332d',
  on_secondary = '#442926',
  on_secondary_container = '#ffdad6',
  on_secondary_fixed = '#2c1513',
  on_secondary_fixed_variant = '#5d3f3c',
  on_surface = '#f1dedc',
  on_surface_variant = '#d8c2bf',
  on_tertiary = '#3f2e04',
  on_tertiary_container = '#fddfa6',
  on_tertiary_fixed = '#261900',
  on_tertiary_fixed_variant = '#584419',
  outline = '#a08c8a',
  outline_variant = '#534341',
  primary = '#ffb4ab',
  primary_container = '#73332d',
  primary_fixed = '#ffdad6',
  primary_fixed_dim = '#ffb4ab',
  scrim = '#000000',
  secondary = '#e7bdb8',
  secondary_container = '#5d3f3c',
  secondary_fixed = '#ffdad6',
  secondary_fixed_dim = '#e7bdb8',
  shadow = '#000000',
  source_color = '#c72020',
  surface = '#1a1110',
  surface_bright = '#423735',
  surface_container = '#271d1c',
  surface_container_high = '#322826',
  surface_container_highest = '#3d3231',
  surface_container_low = '#231918',
  surface_container_lowest = '#140c0b',
  surface_dim = '#1a1110',
  surface_tint = '#ffb4ab',
  surface_variant = '#534341',
  tertiary = '#e0c38c',
  tertiary_container = '#584419',
  tertiary_fixed = '#fddfa6',
  tertiary_fixed_dim = '#e0c38c',
}

local lualine_theme = {
  normal = {
    a = { bg = c.primary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  insert = {
    a = { bg = c.tertiary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  visual = {
    a = { bg = c.secondary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  replace = {
    a = { bg = c.error, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  command = {
    a = { bg = c.error, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  inactive = {
    a = { bg = c.background, fg = c.on_surface, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
}

require('lualine').setup {
  options = { theme = lualine_theme },
}

vim.o.termguicolors = true
vim.api.nvim_set_hl(0, 'WhichKey', { fg = c.error })
vim.api.nvim_set_hl(0, 'WhichKeyDesc', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'WhichKeyGroup', { fg = c.primary })

vim.api.nvim_set_hl(0, 'Normal', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'NormalLBC', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'LineNr', { fg = c.on_surface_variant })
vim.api.nvim_set_hl(0, 'LineNrAbove', { fg = c.surface_variant })
vim.api.nvim_set_hl(0, 'LineNrBelow', { fg = c.surface_variant })
vim.api.nvim_set_hl(0, 'Comment', { fg = c.surface_variant })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = c.primary })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'FloatTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'FloatFooter', { fg = c.primary })

vim.api.nvim_set_hl(0, 'TelescopeNormal', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePromptBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeResultsBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePreviewBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePromptTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeResultsTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeSelection', { bg = c.surface_container, bold = true })
vim.api.nvim_set_hl(0, 'TelescopeMatching', { fg = c.primary, bold = true })
vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', { fg = c.primary, bold = true })

vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePopup', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'Search', { fg = c.on_tertiary, bg = c.tertiary })
vim.api.nvim_set_hl(0, 'NoiceCmdlineIconSearch', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorderSearch', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePrompt', { fg = c.primary, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'NoiceCmdlineIcon', { fg = c.primary, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdline', { fg = c.primary, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'NotifyBackground', { bg = '#000000' })
require('notify').setup {
  background_colour = 'NotifyBackground',
}
