-- Auto-generated by Matugen

local c = {
  background = '#121318',
  background_custom = '#b6c4ff',
  background_custom_container = '#344479',
  background_custom_source = '#121318',
  background_custom_value = '#121318',
  error = '#ffb4ab',
  error_container = '#93000a',
  inverse_on_surface = '#2f3036',
  inverse_primary = '#4f5b92',
  inverse_surface = '#e3e1e9',
  on_background = '#e3e1e9',
  on_background_custom = '#1d2d61',
  on_background_custom_container = '#dce1ff',
  on_error = '#690005',
  on_error_container = '#ffdad6',
  on_primary = '#1f2c61',
  on_primary_container = '#dde1ff',
  on_primary_fixed = '#06164b',
  on_primary_fixed_variant = '#374379',
  on_secondary = '#2c2f42',
  on_secondary_container = '#dfe1f9',
  on_secondary_fixed = '#171b2c',
  on_secondary_fixed_variant = '#424659',
  on_surface = '#e3e1e9',
  on_surface_variant = '#c6c5d0',
  on_tertiary = '#44273f',
  on_tertiary_container = '#ffd7f4',
  on_tertiary_fixed = '#2c1229',
  on_tertiary_fixed_variant = '#5c3d56',
  outline = '#90909a',
  outline_variant = '#45464f',
  primary = '#b8c4ff',
  primary_container = '#374379',
  primary_fixed = '#dde1ff',
  primary_fixed_dim = '#b8c4ff',
  scrim = '#000000',
  secondary = '#c2c5dd',
  secondary_container = '#424659',
  secondary_fixed = '#dfe1f9',
  secondary_fixed_dim = '#c2c5dd',
  shadow = '#000000',
  source_color = '#b2b6d2',
  surface = '#121318',
  surface_bright = '#38393f',
  surface_container = '#1f1f25',
  surface_container_high = '#292a2f',
  surface_container_highest = '#34343a',
  surface_container_low = '#1b1b21',
  surface_container_lowest = '#0d0e13',
  surface_dim = '#121318',
  surface_tint = '#b8c4ff',
  surface_variant = '#45464f',
  tertiary = '#e4bad9',
  tertiary_container = '#5c3d56',
  tertiary_fixed = '#ffd7f4',
  tertiary_fixed_dim = '#e4bad9',
}

local lualine_theme = {
  normal = {
    a = { bg = c.primary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  insert = {
    a = { bg = c.tertiary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  visual = {
    a = { bg = c.secondary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  replace = {
    a = { bg = c.error, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  command = {
    a = { bg = c.error, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  inactive = {
    a = { bg = c.background, fg = c.on_surface, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
}

require('lualine').setup {
  options = { theme = lualine_theme },
}

vim.o.termguicolors = true

vim.api.nvim_set_hl(0, 'StatusLine', { bg = 'NONE' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { bg = 'NONE' })

vim.api.nvim_set_hl(0, 'WhichKey', { fg = c.error })
vim.api.nvim_set_hl(0, 'WhichKeyDesc', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'WhichKeyGroup', { fg = c.primary })
vim.api.nvim_set_hl(0, 'WhichKeySeparator', { fg = c.on_background })

vim.api.nvim_set_hl(0, 'Normal', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = c.on_background })

vim.api.nvim_set_hl(0, 'LineNr', { fg = c.on_surface_variant })
vim.api.nvim_set_hl(0, 'LineNrAbove', { fg = c.surface_variant })
vim.api.nvim_set_hl(0, 'LineNrBelow', { fg = c.surface_variant })

vim.api.nvim_set_hl(0, 'Comment', { fg = c.surface_variant })
vim.api.nvim_set_hl(0, 'Identifier', { fg = c.on_primary })

vim.api.nvim_set_hl(0, 'CursorLine', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = c.primary })

vim.api.nvim_set_hl(0, 'FloatBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'FloatTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'FloatFooter', { fg = c.primary })
vim.api.nvim_set_hl(0, 'PmenuBorder', { fg = c.primary })

vim.api.nvim_set_hl(0, 'TelescopeNormal', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePromptBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeResultsBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePreviewBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePromptTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeResultsTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeSelection', { bg = c.surface_container, bold = true })
vim.api.nvim_set_hl(0, 'TelescopeMatching', { fg = c.primary, bold = true })
vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', { fg = c.primary, bold = true })

vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorderLua', { fg = c.primary })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePopup', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'Search', { fg = c.on_tertiary, bg = c.tertiary })
vim.api.nvim_set_hl(0, 'NoiceCmdlineIconSearch', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorderSearch', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePrompt', { fg = c.primary, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'NoiceCmdlineIcon', { fg = c.primary, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdline', { fg = c.primary, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'BlinkCmpMenuBorder', { fg = c.primary, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'TabLine', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = c.on_primary, bg = c.primary, bold = true })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = c.background })
vim.api.nvim_set_hl(0, 'TabLineIcon', { fg = c.primary, bg = 'NONE', bold = true })

vim.api.nvim_set_hl(0, 'NotifyBackground', { bg = '#000000' })
require('notify').setup { background_colour = 'NotifyBackground' }

function _G.CustomTabLine()
  local line = ''
  local current = vim.fn.tabpagenr()
  local total = vim.fn.tabpagenr '$'

  if total <= 1 then
    return ''
  end

  for i = 1, total do
    local bufnr = vim.fn.tabpagebuflist(i)[1]
    local name = vim.fn.fnamemodify(vim.fn.bufname(bufnr), ':t')
    if name == '' then
      name = '[No Name]'
    end
    local win_count = #vim.fn.gettabinfo(i)[1].windows

    -- tạo label đầy đủ [số file]
    local label = i .. ' ' .. name

    if i == current then
      -- Tab active: góc trái & phải + space sau tab
      line = line .. '%#TabLineIcon#' .. '%#TabLineSel# ' .. label .. ' %*' .. '%#TabLineIcon#'
    else
      -- Tab inactive: label + space trước/sau để cách tab
      line = line .. '  ' .. '%#TabLine#' .. label .. '%*  '
    end
  end

  line = line .. '%#TabLineFill#'
  return line
end

vim.o.tabline = '%!v:lua.CustomTabLine()'

-- Remove italic/bold if you want normal font
vim.api.nvim_set_hl(0, 'AlphaShortcut', { fg = c.tertiary, italic = false, bold = false })
vim.api.nvim_set_hl(0, 'AlphaButtons', { fg = c.secondary, italic = false, bold = false })
vim.api.nvim_set_hl(0, 'AlphaFooter', { fg = c.on_surface_variant, italic = false, bold = false })
vim.api.nvim_set_hl(0, 'AlphaHeader', { fg = c.primary, italic = false, bold = false })
vim.api.nvim_set_hl(0, 'AlphaHeaderLabel', { fg = c.on_surface_variant, italic = false, bold = false })

vim.api.nvim_set_hl(0, 'SnacksNormal', { fg = c.primary, bg = 'none' })
vim.api.nvim_set_hl(0, 'SnacksKey', { fg = c.error, bg = 'none' })
