name = "Matugen Nyaa"

bg = "Reset"
fg = "#bfc8cc"

border = "Rounded"
border_color = "#40484b"
border_focused_color = "#87d1eb"

hl_bg = "#252b2d"

solid_bg = "#87d1eb"
solid_fg = "#003543"

success = "#87d1eb"
error = "#ffb4ab"
info = "#87d1eb"
warning = "#c2c3eb"
