name = "Matugen Nyaa"

bg = "Reset"
fg = "#bfc9c4"

border = "Rounded"
border_color = "#3f4945"
border_focused_color = "#86d6bf"

hl_bg = "#252b29"

solid_bg = "#86d6bf"
solid_fg = "#00382d"

success = "#86d6bf"
error = "#ffb4ab"
info = "#86d6bf"
warning = "#a9cbe3"
