name = "Matugen Nyaa"

bg = "Reset"
fg = "#bfc8cb"

border = "Rounded"
border_color = "#40484b"
border_focused_color = "#85d2e8"

hl_bg = "#252b2d"

solid_bg = "#85d2e8"
solid_fg = "#003641"

success = "#85d2e8"
error = "#ffb4ab"
info = "#85d2e8"
warning = "#c0c4eb"
