-- Auto-generated by Matugen

local c = {
  background = '{{colors.background.default.hex}}',
  background_custom = '{{colors.background_custom.default.hex}}',
  background_custom_container = '{{colors.background_custom_container.default.hex}}',
  background_custom_source = '{{colors.background_custom_source.default.hex}}',
  background_custom_value = '{{colors.background_custom_value.default.hex}}',
  error = '{{colors.error.default.hex}}',
  error_container = '{{colors.error_container.default.hex}}',
  inverse_on_surface = '{{colors.inverse_on_surface.default.hex}}',
  inverse_primary = '{{colors.inverse_primary.default.hex}}',
  inverse_surface = '{{colors.inverse_surface.default.hex}}',
  on_background = '{{colors.on_background.default.hex}}',
  on_background_custom = '{{colors.on_background_custom.default.hex}}',
  on_background_custom_container = '{{colors.on_background_custom_container.default.hex}}',
  on_error = '{{colors.on_error.default.hex}}',
  on_error_container = '{{colors.on_error_container.default.hex}}',
  on_primary = '{{colors.on_primary.default.hex}}',
  on_primary_container = '{{colors.on_primary_container.default.hex}}',
  on_primary_fixed = '{{colors.on_primary_fixed.default.hex}}',
  on_primary_fixed_variant = '{{colors.on_primary_fixed_variant.default.hex}}',
  on_secondary = '{{colors.on_secondary.default.hex}}',
  on_secondary_container = '{{colors.on_secondary_container.default.hex}}',
  on_secondary_fixed = '{{colors.on_secondary_fixed.default.hex}}',
  on_secondary_fixed_variant = '{{colors.on_secondary_fixed_variant.default.hex}}',
  on_surface = '{{colors.on_surface.default.hex}}',
  on_surface_variant = '{{colors.on_surface_variant.default.hex}}',
  on_tertiary = '{{colors.on_tertiary.default.hex}}',
  on_tertiary_container = '{{colors.on_tertiary_container.default.hex}}',
  on_tertiary_fixed = '{{colors.on_tertiary_fixed.default.hex}}',
  on_tertiary_fixed_variant = '{{colors.on_tertiary_fixed_variant.default.hex}}',
  outline = '{{colors.outline.default.hex}}',
  outline_variant = '{{colors.outline_variant.default.hex}}',
  primary = '{{colors.primary.default.hex}}',
  primary_container = '{{colors.primary_container.default.hex}}',
  primary_fixed = '{{colors.primary_fixed.default.hex}}',
  primary_fixed_dim = '{{colors.primary_fixed_dim.default.hex}}',
  scrim = '{{colors.scrim.default.hex}}',
  secondary = '{{colors.secondary.default.hex}}',
  secondary_container = '{{colors.secondary_container.default.hex}}',
  secondary_fixed = '{{colors.secondary_fixed.default.hex}}',
  secondary_fixed_dim = '{{colors.secondary_fixed_dim.default.hex}}',
  shadow = '{{colors.shadow.default.hex}}',
  source_color = '{{colors.source_color.default.hex}}',
  surface = '{{colors.surface.default.hex}}',
  surface_bright = '{{colors.surface_bright.default.hex}}',
  surface_container = '{{colors.surface_container.default.hex}}',
  surface_container_high = '{{colors.surface_container_high.default.hex}}',
  surface_container_highest = '{{colors.surface_container_highest.default.hex}}',
  surface_container_low = '{{colors.surface_container_low.default.hex}}',
  surface_container_lowest = '{{colors.surface_container_lowest.default.hex}}',
  surface_dim = '{{colors.surface_dim.default.hex}}',
  surface_tint = '{{colors.surface_tint.default.hex}}',
  surface_variant = '{{colors.surface_variant.default.hex}}',
  tertiary = '{{colors.tertiary.default.hex}}',
  tertiary_container = '{{colors.tertiary_container.default.hex}}',
  tertiary_fixed = '{{colors.tertiary_fixed.default.hex}}',
  tertiary_fixed_dim = '{{colors.tertiary_fixed_dim.default.hex}}',
}

local lualine_theme = {
  normal = {
    a = { bg = c.primary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  insert = {
    a = { bg = c.tertiary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  visual = {
    a = { bg = c.secondary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  replace = {
    a = { bg = c.error, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  command = {
    a = { bg = c.error, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  inactive = {
    a = { bg = c.background, fg = c.on_surface, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
}

require('lualine').setup {
  options = { theme = lualine_theme },
}

vim.o.termguicolors = true
vim.api.nvim_set_hl(0, 'WhichKey', { fg = c.error })
vim.api.nvim_set_hl(0, 'WhichKeyDesc', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'WhichKeyGroup', { fg = c.primary })

vim.api.nvim_set_hl(0, 'Normal', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'NormalLBC', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'LineNr', { fg = c.on_surface_variant })
vim.api.nvim_set_hl(0, 'LineNrAbove', { fg = c.surface_variant })
vim.api.nvim_set_hl(0, 'LineNrBelow', { fg = c.surface_variant })
vim.api.nvim_set_hl(0, 'Comment', { fg = c.surface_variant })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = c.primary })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'FloatTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'FloatFooter', { fg = c.primary })

vim.api.nvim_set_hl(0, 'TelescopeNormal', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePromptBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeResultsBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePreviewBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePromptTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeResultsTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeSelection', { bg = c.surface_container, bold = true })
vim.api.nvim_set_hl(0, 'TelescopeMatching', { fg = c.primary, bold = true })
vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', { fg = c.primary, bold = true })

vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePopup', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'Search', { fg = c.on_tertiary, bg = c.tertiary })
vim.api.nvim_set_hl(0, 'NoiceCmdlineIconSearch', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorderSearch', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePrompt', { fg = c.primary, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'NoiceCmdlineIcon', { fg = c.primary, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdline', { fg = c.primary, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'NotifyBackground', { bg = '#000000' })
require('notify').setup {
  background_colour = 'NotifyBackground',
}
