-- Auto-generated by Matugen

local c = {
  background = '{{colors.background.default.hex}}',
  background_custom = '{{colors.background_custom.default.hex}}',
  background_custom_container = '{{colors.background_custom_container.default.hex}}',
  background_custom_source = '{{colors.background_custom_source.default.hex}}',
  background_custom_value = '{{colors.background_custom_value.default.hex}}',
  error = '{{colors.error.default.hex}}',
  error_container = '{{colors.error_container.default.hex}}',
  inverse_on_surface = '{{colors.inverse_on_surface.default.hex}}',
  inverse_primary = '{{colors.inverse_primary.default.hex}}',
  inverse_surface = '{{colors.inverse_surface.default.hex}}',
  on_background = '{{colors.on_background.default.hex}}',
  on_background_custom = '{{colors.on_background_custom.default.hex}}',
  on_background_custom_container = '{{colors.on_background_custom_container.default.hex}}',
  on_error = '{{colors.on_error.default.hex}}',
  on_error_container = '{{colors.on_error_container.default.hex}}',
  on_primary = '{{colors.on_primary.default.hex}}',
  on_primary_container = '{{colors.on_primary_container.default.hex}}',
  on_primary_fixed = '{{colors.on_primary_fixed.default.hex}}',
  on_primary_fixed_variant = '{{colors.on_primary_fixed_variant.default.hex}}',
  on_secondary = '{{colors.on_secondary.default.hex}}',
  on_secondary_container = '{{colors.on_secondary_container.default.hex}}',
  on_secondary_fixed = '{{colors.on_secondary_fixed.default.hex}}',
  on_secondary_fixed_variant = '{{colors.on_secondary_fixed_variant.default.hex}}',
  on_surface = '{{colors.on_surface.default.hex}}',
  on_surface_variant = '{{colors.on_surface_variant.default.hex}}',
  on_tertiary = '{{colors.on_tertiary.default.hex}}',
  on_tertiary_container = '{{colors.on_tertiary_container.default.hex}}',
  on_tertiary_fixed = '{{colors.on_tertiary_fixed.default.hex}}',
  on_tertiary_fixed_variant = '{{colors.on_tertiary_fixed_variant.default.hex}}',
  outline = '{{colors.outline.default.hex}}',
  outline_variant = '{{colors.outline_variant.default.hex}}',
  primary = '{{colors.primary.default.hex}}',
  primary_container = '{{colors.primary_container.default.hex}}',
  primary_fixed = '{{colors.primary_fixed.default.hex}}',
  primary_fixed_dim = '{{colors.primary_fixed_dim.default.hex}}',
  scrim = '{{colors.scrim.default.hex}}',
  secondary = '{{colors.secondary.default.hex}}',
  secondary_container = '{{colors.secondary_container.default.hex}}',
  secondary_fixed = '{{colors.secondary_fixed.default.hex}}',
  secondary_fixed_dim = '{{colors.secondary_fixed_dim.default.hex}}',
  shadow = '{{colors.shadow.default.hex}}',
  source_color = '{{colors.source_color.default.hex}}',
  surface = '{{colors.surface.default.hex}}',
  surface_bright = '{{colors.surface_bright.default.hex}}',
  surface_container = '{{colors.surface_container.default.hex}}',
  surface_container_high = '{{colors.surface_container_high.default.hex}}',
  surface_container_highest = '{{colors.surface_container_highest.default.hex}}',
  surface_container_low = '{{colors.surface_container_low.default.hex}}',
  surface_container_lowest = '{{colors.surface_container_lowest.default.hex}}',
  surface_dim = '{{colors.surface_dim.default.hex}}',
  surface_tint = '{{colors.surface_tint.default.hex}}',
  surface_variant = '{{colors.surface_variant.default.hex}}',
  tertiary = '{{colors.tertiary.default.hex}}',
  tertiary_container = '{{colors.tertiary_container.default.hex}}',
  tertiary_fixed = '{{colors.tertiary_fixed.default.hex}}',
  tertiary_fixed_dim = '{{colors.tertiary_fixed_dim.default.hex}}',
}

local lualine_theme = {
  normal = {
    a = { bg = c.primary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  insert = {
    a = { bg = c.tertiary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  visual = {
    a = { bg = c.secondary, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  replace = {
    a = { bg = c.error, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  command = {
    a = { bg = c.error, fg = c.background, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
  inactive = {
    a = { bg = c.background, fg = c.on_surface, gui = 'bold' },
    b = { bg = c.surface_container, fg = c.on_surface },
    c = { bg = c.surface_container, fg = c.on_surface },
  },
}

require('lualine').setup {
  options = { theme = lualine_theme },
}

vim.o.termguicolors = true

vim.api.nvim_set_hl(0, 'StatusLine', { bg = 'NONE' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { bg = 'NONE' })

vim.api.nvim_set_hl(0, 'WhichKey', { fg = c.error })
vim.api.nvim_set_hl(0, 'WhichKeyDesc', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'WhichKeyGroup', { fg = c.primary })
vim.api.nvim_set_hl(0, 'WhichKeySeparator', { fg = c.on_background })

vim.api.nvim_set_hl(0, 'Normal', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = c.on_background })

vim.api.nvim_set_hl(0, 'LineNr', { fg = c.on_surface_variant })
vim.api.nvim_set_hl(0, 'LineNrAbove', { fg = c.surface_variant })
vim.api.nvim_set_hl(0, 'LineNrBelow', { fg = c.surface_variant })

vim.api.nvim_set_hl(0, 'Comment', { fg = c.surface_variant })
vim.api.nvim_set_hl(0, 'Identifier', { fg = c.on_primary })

vim.api.nvim_set_hl(0, 'CursorLine', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = c.primary })

vim.api.nvim_set_hl(0, 'FloatBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'FloatTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'FloatFooter', { fg = c.primary })
vim.api.nvim_set_hl(0, 'PmenuBorder', { fg = c.primary })

vim.api.nvim_set_hl(0, 'TelescopeNormal', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePromptBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeResultsBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePreviewBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePromptTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeResultsTitle', { fg = c.primary })
vim.api.nvim_set_hl(0, 'TelescopeSelection', { bg = c.surface_container, bold = true })
vim.api.nvim_set_hl(0, 'TelescopeMatching', { fg = c.primary, bold = true })
vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', { fg = c.primary, bold = true })

vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorderLua', { fg = c.primary })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorder', { fg = c.primary })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePopup', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'Search', { fg = c.on_tertiary, bg = c.tertiary })
vim.api.nvim_set_hl(0, 'NoiceCmdlineIconSearch', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorderSearch', { fg = c.on_background, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdlinePrompt', { fg = c.primary, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'NoiceCmdlineIcon', { fg = c.primary, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NoiceCmdline', { fg = c.primary, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'BlinkCmpMenuBorder', { fg = c.primary, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'TabLine', { fg = c.on_background })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = c.on_primary, bg = c.primary, bold = true })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = c.background })
vim.api.nvim_set_hl(0, 'TabLineIcon', { fg = c.primary, bg = 'NONE', bold = true })

vim.api.nvim_set_hl(0, 'NotifyBackground', { bg = '#000000' })
require('notify').setup { background_colour = 'NotifyBackground' }

function _G.CustomTabLine()
  local line = ''
  local current = vim.fn.tabpagenr()
  local total = vim.fn.tabpagenr '$'

  if total <= 1 then
    return ''
  end

  for i = 1, total do
    local bufnr = vim.fn.tabpagebuflist(i)[1]
    local name = vim.fn.fnamemodify(vim.fn.bufname(bufnr), ':t')
    if name == '' then
      name = '[No Name]'
    end
    local win_count = #vim.fn.gettabinfo(i)[1].windows

    -- tạo label đầy đủ [số file]
    local label = i .. ' ' .. name

    if i == current then
      -- Tab active: góc trái & phải + space sau tab
      line = line .. '%#TabLineIcon#' .. '%#TabLineSel# ' .. label .. ' %*' .. '%#TabLineIcon#'
    else
      -- Tab inactive: label + space trước/sau để cách tab
      line = line .. '  ' .. '%#TabLine#' .. label .. '%*  '
    end
  end

  line = line .. '%#TabLineFill#'
  return line
end

vim.o.tabline = '%!v:lua.CustomTabLine()'

-- Remove italic/bold if you want normal font
vim.api.nvim_set_hl(0, 'AlphaShortcut', { fg = c.tertiary, italic = false, bold = false })
vim.api.nvim_set_hl(0, 'AlphaButtons', { fg = c.secondary, italic = false, bold = false })
vim.api.nvim_set_hl(0, 'AlphaFooter', { fg = c.on_surface_variant, italic = false, bold = false })
vim.api.nvim_set_hl(0, 'AlphaHeader', { fg = c.primary, italic = false, bold = false })
vim.api.nvim_set_hl(0, 'AlphaHeaderLabel', { fg = c.on_surface_variant, italic = false, bold = false })

vim.api.nvim_set_hl(0, 'SnacksNormal', { fg = c.primary, bg = 'none' })
vim.api.nvim_set_hl(0, 'SnacksKey', { fg = c.error, bg = 'none' })

-- =========================================================
-- render-markdown.nvim highlight groups (Matugen themed)
-- =========================================================

-- ======================
-- Headings (icons)
-- ======================
vim.api.nvim_set_hl(0, 'RenderMarkdownH1', { fg = c.primary, bold = true })
vim.api.nvim_set_hl(0, 'RenderMarkdownH2', { fg = c.secondary, bold = true })
vim.api.nvim_set_hl(0, 'RenderMarkdownH3', { fg = c.tertiary })
vim.api.nvim_set_hl(0, 'RenderMarkdownH4', { fg = c.on_surface_variant })
vim.api.nvim_set_hl(0, 'RenderMarkdownH5', { fg = c.outline })
vim.api.nvim_set_hl(0, 'RenderMarkdownH6', { fg = c.outline_variant })

-- ======================
-- Heading background lines
-- ======================
vim.api.nvim_set_hl(0, 'RenderMarkdownH1Bg', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'RenderMarkdownH2Bg', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'RenderMarkdownH3Bg', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'RenderMarkdownH4Bg', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'RenderMarkdownH5Bg', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'RenderMarkdownH6Bg', { bg = c.surface_container })

-- ======================
-- Code blocks
-- ======================
vim.api.nvim_set_hl(0, 'RenderMarkdownCode', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'RenderMarkdownCodeBorder', { bg = c.surface_container_high })
vim.api.nvim_set_hl(0, 'RenderMarkdownCodeInline', {
  fg = c.on_surface,
  bg = c.surface_container_highest,
})
vim.api.nvim_set_hl(0, 'RenderMarkdownCodeInfo', {
  fg = c.primary,
  italic = true,
})
vim.api.nvim_set_hl(0, 'RenderMarkdownCodeFallback', {
  fg = c.on_surface_variant,
})

-- ======================
-- Quotes
-- ======================
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote', {
  fg = c.on_surface_variant,
  italic = true,
})
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote1', { fg = c.primary })
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote2', { fg = c.secondary })
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote3', { fg = c.tertiary })
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote4', { fg = c.primary_container })
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote5', { fg = c.secondary_container })
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote6', { fg = c.surface_variant })

-- ======================
-- Lists & structure
-- ======================
vim.api.nvim_set_hl(0, 'RenderMarkdownBullet', { fg = c.primary })
vim.api.nvim_set_hl(0, 'RenderMarkdownIndent', { fg = c.surface_variant })
vim.api.nvim_set_hl(0, 'RenderMarkdownDash', { fg = c.outline_variant })
vim.api.nvim_set_hl(0, 'RenderMarkdownSign', { bg = c.background })

-- ======================
-- Links
-- ======================
vim.api.nvim_set_hl(0, 'RenderMarkdownLink', {
  fg = c.primary,
  underline = true,
})
vim.api.nvim_set_hl(0, 'RenderMarkdownWikiLink', {
  fg = c.secondary,
  underline = true,
})

-- ======================
-- Inline highlight
-- ======================
vim.api.nvim_set_hl(0, 'RenderMarkdownInlineHighlight', {
  fg = c.on_surface,
  bg = c.surface_container_highest,
})

-- ======================
-- Checkboxes
-- ======================
vim.api.nvim_set_hl(0, 'RenderMarkdownUnchecked', { fg = c.outline })
vim.api.nvim_set_hl(0, 'RenderMarkdownChecked', {
  fg = c.primary,
  bold = true,
})
vim.api.nvim_set_hl(0, 'RenderMarkdownTodo', { fg = c.tertiary })

-- ======================
-- Tables
-- ======================
vim.api.nvim_set_hl(0, 'RenderMarkdownTableHead', {
  fg = c.primary,
  bold = true,
})
vim.api.nvim_set_hl(0, 'RenderMarkdownTableRow', { fg = c.on_surface })
vim.api.nvim_set_hl(0, 'RenderMarkdownTableFill', { fg = c.surface_variant })

-- ======================
-- Math & HTML
-- ======================
vim.api.nvim_set_hl(0, 'RenderMarkdownMath', { fg = c.secondary })
vim.api.nvim_set_hl(0, 'RenderMarkdownHtmlComment', {
  fg = c.outline_variant,
  italic = true,
})

-- ======================
-- Callouts
-- ======================
vim.api.nvim_set_hl(0, 'RenderMarkdownSuccess', { fg = c.primary })
vim.api.nvim_set_hl(0, 'RenderMarkdownInfo', { fg = c.secondary })
vim.api.nvim_set_hl(0, 'RenderMarkdownHint', { fg = c.tertiary })
vim.api.nvim_set_hl(0, 'RenderMarkdownWarn', { fg = c.error })
vim.api.nvim_set_hl(0, 'RenderMarkdownError', { fg = c.error, bold = true })

-- Bullets & Dash
vim.api.nvim_set_hl(0, 'RenderMarkdownBullet', { fg = c.primary })
vim.api.nvim_set_hl(0, 'RenderMarkdownDash', { fg = c.outline_variant })

-- Code
vim.api.nvim_set_hl(0, 'RenderMarkdownCode', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'RenderMarkdownCodeInline', { fg = c.on_surface, bg = c.surface_container_highest })
vim.api.nvim_set_hl(0, 'RenderMarkdownCodeBorder', { bg = c.surface_container_high })
vim.api.nvim_set_hl(0, 'RenderMarkdownCodeInfo', { fg = c.primary, italic = true })
vim.api.nvim_set_hl(0, 'RenderMarkdownCodeFallback', { fg = c.on_surface_variant })

-- Table
vim.api.nvim_set_hl(0, 'RenderMarkdownTableHead', { fg = c.primary, bold = true })
vim.api.nvim_set_hl(0, 'RenderMarkdownTableRow', { fg = c.on_surface })
vim.api.nvim_set_hl(0, 'RenderMarkdownTableFill', { fg = c.surface_variant })

-- Raw / inline markdown
vim.api.nvim_set_hl(0, '@markup.raw.markdown_inline', { fg = c.primary, bg = c.surface_container })

-- Headings H1-H7
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH1Fg', { fg = c.primary, bold = true })
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH1Bg', { bg = c.primary_container })
--
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH2Fg', { fg = c.secondary, bold = true })
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH2Bg', { bg = c.secondary_container })
--
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH3Fg', { fg = c.tertiary, bold = true })
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH3Bg', { bg = c.surface_container })
--
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH4Fg', { fg = c.on_surface_variant, bold = true })
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH4Bg', { bg = c.surface_container_low })
--
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH5Fg', { fg = c.outline, bold = true })
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH5Bg', { bg = c.surface_container_lowest })
--
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH6Fg', { fg = c.on_surface_variant, bold = true })
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH6Bg', { bg = c.surface_dim })
--
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH7Fg', { fg = c.primary_container, bold = true })
-- vim.api.nvim_set_hl(0, 'RenderMarkdownH7Bg', { bg = c.surface_variant })

-- Quotes
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote', { fg = c.on_surface_variant, italic = true })
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote1', { fg = c.primary })
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote2', { fg = c.secondary })
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote3', { fg = c.tertiary })
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote4', { fg = c.primary_container })
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote5', { fg = c.secondary_container })
vim.api.nvim_set_hl(0, 'RenderMarkdownQuote6', { fg = c.surface_variant })

-- Links
vim.api.nvim_set_hl(0, 'RenderMarkdownLink', { fg = c.primary, underline = true })
vim.api.nvim_set_hl(0, 'RenderMarkdownWikiLink', { fg = c.secondary, underline = true })

-- Inline highlight
vim.api.nvim_set_hl(0, 'RenderMarkdownInlineHighlight', { fg = c.on_surface, bg = c.surface_container_highest })

-- Checkboxes
vim.api.nvim_set_hl(0, 'RenderMarkdownUnchecked', { fg = c.outline })
vim.api.nvim_set_hl(0, 'RenderMarkdownChecked', { fg = c.primary, bold = true })
vim.api.nvim_set_hl(0, 'RenderMarkdownTodo', { fg = c.tertiary })

-- Math & HTML
vim.api.nvim_set_hl(0, 'RenderMarkdownMath', { fg = c.secondary })
vim.api.nvim_set_hl(0, 'RenderMarkdownHtmlComment', { fg = c.outline_variant, italic = true })

-- Callouts
vim.api.nvim_set_hl(0, 'RenderMarkdownSuccess', { fg = c.primary })
vim.api.nvim_set_hl(0, 'RenderMarkdownInfo', { fg = c.secondary })
vim.api.nvim_set_hl(0, 'RenderMarkdownHint', { fg = c.tertiary })
vim.api.nvim_set_hl(0, 'RenderMarkdownWarn', { fg = c.error })
vim.api.nvim_set_hl(0, 'RenderMarkdownError', { fg = c.error, bold = true })

-- Headings
vim.api.nvim_set_hl(0, 'markdownH1', { fg = c.primary, bold = true })
vim.api.nvim_set_hl(0, 'markdownH2', { fg = c.secondary, bold = true })
vim.api.nvim_set_hl(0, 'markdownH3', { fg = c.tertiary, bold = true })
vim.api.nvim_set_hl(0, 'markdownH4', { fg = c.on_surface_variant, bold = true })
vim.api.nvim_set_hl(0, 'markdownH5', { fg = c.outline, bold = true })
vim.api.nvim_set_hl(0, 'markdownH6', { fg = c.outline_variant, bold = true })

-- Blockquote
vim.api.nvim_set_hl(0, 'markdownBlockquote', { fg = c.outline, italic = true })

-- List markers
vim.api.nvim_set_hl(0, 'markdownListMarker', { fg = c.primary })
vim.api.nvim_set_hl(0, 'markdownOrderedListMarker', { fg = c.primary })

-- Code blocks & inline code
vim.api.nvim_set_hl(0, 'markdownCodeBlock', { bg = c.surface_container })
vim.api.nvim_set_hl(0, 'markdownCode', { bg = c.surface_container, fg = c.on_surface })
vim.api.nvim_set_hl(0, 'markdownCodeDelimiter', { fg = c.on_surface })
vim.api.nvim_set_hl(0, 'markdownCodeBlock', { bg = c.surface_container })

-- Rules / HR / line breaks
vim.api.nvim_set_hl(0, 'markdownRule', { fg = c.outline })
vim.api.nvim_set_hl(0, 'markdownHeadingRule', { fg = c.outline })
vim.api.nvim_set_hl(0, 'markdownLineBreak', { fg = c.outline })

-- Links
vim.api.nvim_set_hl(0, 'markdownLinkText', { fg = c.primary, underline = true })
vim.api.nvim_set_hl(0, 'markdownLink', { fg = c.primary, underline = true })
vim.api.nvim_set_hl(0, 'markdownUrl', { fg = c.secondary, underline = true })

-- Emphasis
vim.api.nvim_set_hl(0, 'markdownItalic', { italic = true, fg = c.secondary })
vim.api.nvim_set_hl(0, 'markdownBold', { bold = true, fg = c.primary })
vim.api.nvim_set_hl(0, 'markdownBoldItalic', { bold = true, italic = true, fg = c.tertiary })
vim.api.nvim_set_hl(0, 'markdownStrike', { fg = c.outline, strikethrough = true })

-- Footnotes / Ids
vim.api.nvim_set_hl(0, 'markdownFootnote', { fg = c.tertiary })
vim.api.nvim_set_hl(0, 'markdownFootnoteDefinition', { fg = c.secondary })
vim.api.nvim_set_hl(0, 'markdownId', { fg = c.primary })

-- Errors
vim.api.nvim_set_hl(0, 'markdownError', { fg = c.error, bold = true })
