-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "",
	base01 = "#0f0d13",
	base02 = "#1c1b20",
	base03 = "#48454e",
	base04 = "#cac4cf",
	base05 = "#e6e1e9",
	base06 = "#312f35",
	base07 = "#3a383e",

	base08 = "#ffb4ab",
	base09 = "#eeb8cb",
	base0A = "#cac3dc",
	base0B = "#cbbeff",
	base0C = "#623b4b",
	base0D = "#cbbeff",
	base0E = "#484458",
	base0F = "#93000a",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#4a3e76",
	fg = "#141318",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#ffd9e5",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#eeb8cb",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#cac3dc",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#625690",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#0f0d13",
	fg = "#cbbeff",
})
